- type: latheRecipePack
  id: SecurityAmmoStaticOmu
  recipes:
  - MagazineShotgunLeverRifleEmpty
  - MagazineShotgunLeverRifle
  - MagazineBoxCaselessRiflePractice
  - MagazineCaselessRiflePractice
  - MagazineCaselessRifleShortPractice
  - MagazineBoxCaselessRifle
  - MagazineCaselessRifle
  - MagazineCaselessRifleShort
  - MagazineMagnumLeverRifle
  - MagazineMagnumLeverRifleEmpty

- type: latheRecipePack
  id: SecurityAmmoOmu
  recipes:
  - MagazineBoxCaselessRifleIncendiary
  - MagazineBoxCaselessRifleUranium
  - MagazineCaselessRifleIncendiary
  - MagazineCaselessRifleUranium
